version: "3.5"

services:

  https-portal:
    container_name: https-portal
    image: steveltn/https-portal:${HTTPS_PORTAL_VERSION}
    environment:
      DOMAINS: >
        jenkins.test -> http://jenkins:8080,
      CLIENT_MAX_BODY_SIZE: 1024M
      SERVER_NAMES_HASH_BUCKET_SIZE: 1024
      STAGE: local
    volumes:
      - https-portal_certs:/var/lib/https-portal
    ports:
      - "80:80"
      - "443:443"
    networks:
      - jenkins
    depends_on:
      - jenkins

  jenkins:
    container_name: jenkins
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - JENKINS_VERSION=${JENKINS_VERSION}
        - BLUEOCEAN_VERSION=${BLUEOCEAN_VERSION}
        - DOCKER_WORKFLOW_VERSION=${DOCKER_WORKFLOW_VERSION}
    expose:
      - 8080
      - 50000
    networks:
      - jenkins
    environment:
      - DOCKER_HOST=${JENKINS_DOCKER_HOST}
      - DOCKER_CERT_PATH=/certs/client
      - DOCKER_TLS_VERIFY=1
    volumes:
      - jenkins-data:/var/jenkins_home
      - ./private/certs:/certs/client:ro

networks:
  jenkins:

volumes:
  https-portal_certs:
  jenkins-data:
